
MYSQL_DATABASE_HOST = 'localhost'
MYSQL_DATABASE_PORT = '33066'
MYSQL_DATABASE_DB = 'itm_project'
MYSQL_DATABASE_USER = 'itm_project'
MYSQL_DATABASE_PASSWORD = 'password'

SQLALCHEMY_DATABASE_URI = f"mysql+pymysql://{MYSQL_DATABASE_USER}:{MYSQL_DATABASE_PASSWORD}@{MYSQL_DATABASE_HOST}:{MYSQL_DATABASE_PORT}/{MYSQL_DATABASE_DB}"
