version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - cd 3-tier-project
  build:
    commands:
      - echo "Stopping existing containers"
      - docker-compose down
      - echo "Building docker images"
      - docker build -t itm_project .
      - echo "Running containers"
      - docker-compose up -d
  post_build:
    commands:
      - printf '[{"name":"app","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json
      - cp imagedefinitions.json ../imagedefinitions.json
      - cd ..

artifacts:
  files: imagedefinitions.json
