version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - cd 3-tier-project
  build:
    commands:
      - echo "Building docker images"
      - aws codebuild start-build --project-name 3rd --output json > build_output.json
      - cat build_output.json # Displaying the content of build_output.json for debugging purposes
      - # Extract image details from build_output.json and save to imagedefinitions.json
      - echo '{"name":"app","imageUri":"your_image_uri"}' > imagedefinitions.json

  post_build:
    commands:
      - cp imagedefinitions.json ../imagedefinitions.json
      - cd ..

artifacts:
  files:
    - imagedefinitions.json

